export const Products = [
  {
    id: 1,
    name: "CAMISETA BLANCA HOMBRE NEW YORK",
    description:
      "Camiseta de algodón blanca con diseño de New York, ideal para un look casual.",
    size: ["M"],
    image: "./camisa_hombre_1.jpg",
    more_images: ["./camisa_hombre_1_1.jpg"],
    price: 15.0,
    activo: true,
  },
  {
    id: 12,
    name: "CAMISETA NEGRA HOMBRE LA",
    description: "Camiseta negra de manga corta con estampado de Los Ángeles.",
    size: ["L"],
    image: "./camisa_hombre_2.jpg",
    more_images: [],
    price: 15.0,
    activo: true,
  },
  {
    id: 2,
    name: "CAMISETA DE RAYAS",
    description:
      "Camiseta colorida con diseño vibrante, perfecto para el verano.",
    size: ["S"],
    image: "./camisa_mujer_1.jpg",
    more_images: [],
    price: 10.0,
    activo: true,
  },
  {
    id: 3,
    name: "FALDA SHORT BLANCA",
    description:
      "Falda short de tela ligera en color blanco, cómoda y elegante.",
    size: ["S"],
    image: "./falda_mujer_1.jpg",
    more_images: ["./falda_mujer_1_1.jpg"],
    price: 15.0,
    activo: true,
  },
  {
    id: 4,
    name: "TOP BLANCO ASIMETRICO",
    description: "Top blanco de seda con un diseño elegante y ligero.",
    size: ["S", "M", "L"],
    image: "./top_mujer_1.jpg",
    more_images: [],
    price: 12.0,
    activo: true,
  },
  {
    id: 5,
    name: "TOP BLANCO CON NUDO FRONTAL",
    description: "Top blanco con detalles de agujetas en la parte delantera.",
    size: ["S"],
    image: "./top_mujer_2.jpg",
    more_images: ["./top_mujer_2_1.jpg"],
    price: 8.0,
    activo: true,
  },
  {
    id: 6,
    name: "TOP AZUL UNICOLOR",
    description: "Top azul unicolor con tela fresca y transpirable.",
    size: ["S"],
    image: "./top_mujer_3.jpg",
    more_images: ["./top_mujer_3_1.jpg"],
    price: 8.0,
    activo: true,
  },
  {
    id: 7,
    name: "TOP SALMON CON TIRANTES",
    description: "Top deportivo con tirantes, ideal para entrenamientos.",
    size: ["M"],
    image: "./top_mujer_4.jpg",
    more_images: ["./top_mujer_4_1.jpg"],
    price: 8.0,
    activo: true,
  },
  {
    id: 8,
    name: "TOP NEGRO ELEGANTE CON BOTONES",
    description:
      "Top negro elegante con botones dorados para un toque sofisticado.",
    size: ["S"],
    image: "./top_mujer_5.jpg",
    more_images: ["./top_mujer_5_1.jpg"],
    price: 15.0,
    activo: true,
  },
  {
    id: 9,
    name: "TOP BLANCO ESTAMPADO MORADO",
    description:
      "Top blanco con estampado morado de flores, ideal para primavera.",
    size: ["S"],
    image: "./top_mujer_6.jpg",
    more_images: ["./top_mujer_6_1.jpg"],
    price: 8.0,
    activo: true,
  },
  {
    id: 10,
    name: "TOP BLANCO ESTAMPADO DE FLORES ROJAS",
    description:
      "Top blanco con estampado floral rojo, con diseño romántico y femenino.",
    size: ["S"],
    image: "./top_mujer_7.jpg",
    more_images: ["./top_mujer_7_1.jpg"],
    price: 12.0,
    activo: true,
  },
  {
    id: 11,
    name: "TOP BLANCO ESTAMPADO FLORES ROSADAS",
    description:
      "Top blanco con estampado de flores rosadas, perfecto para un look fresco.",
    size: ["M"],
    image: "./top_mujer_8.jpg",
    more_images: [],
    price: 10.0,
    activo: true,
  },
  {
    id: 13,
    name: "BANDANA ROSADA",
    description: "perfecto para un look fresco.",
    size: ["M"],
    image: "./bandana_rosada_1.jpg",
    more_images: [],
    price: 10.0,
    activo: true,
  },
  {
    id: 14,
    name: "BANDANA BEIGE CON ESTAMPADO",
    description: "perfecto para un look atrevido.",
    size: ["M"],
    image: "./bandana_beige_1.jpg",
    more_images: [],
    price: 10.0,
    activo: true,
  },
  {
    id: 15,
    name: "CORSET NEGRO",
    description: "perfecto para un look atrevido.",
    size: ["S", "M", "XL"],
    image: "./corset_negro_1.jpg",
    more_images: ["./corset_negro_1_1.jpg"],
    price: 25.0,
    activo: true,
  },
  {
    id: 16,
    name: "CORSET BLANCO",
    description: "perfecto para un look atrevido.",
    size: ["S", "L"],
    image: "./corset_blanco_1.jpg",
    more_images: ["./corset_blanco_1_1.jpg"],
    price: 25.0,
    activo: true,
  },
  {
    id: 17,
    name: "CORSET ROSADO",
    description: "perfecto para un look atrevido.",
    size: ["S"],
    image: "./corset_rosado_1.jpg",
    more_images: ["./corset_rosado_1_1.jpg"],
    price: 25.0,
    activo: true,
  },
  {
    id: 18,
    name: "CAMISETA BLANCA PARA DAMA MARGARITA",
    description: "perfecto para un look atrevido.",
    size: ["M"],
    image: "./camiseta_mujer_margarita_1.jpg",
    more_images: ["./camiseta_mujer_margarita_1_1.jpg"],
    price: 10.0,
    activo: true,
  },
  {
    id: 19,
    name: "TOP SENCILLO NEGRO CON BLANCO ",
    description: "perfecto para un look atrevido.",
    size: ["S"],
    image: "./top_mujer_9.jpg",
    more_images: [],
    price: 8.0,
    activo: true,
  },
  {
    id: 21,
    name: "TOP BLANCO ESTAMPADO NEGRO",
    description: "perfecto para un look atrevido.",
    size: ["S"],
    image: "./top_mujer_10.jpg",
    more_images: ["./top_mujer_10_1.jpg"],
    price: 10.0,
    activo: true,
  },
  {
    id: 22,
    name: "SHORT AMARILLO DEPORTIVO",
    description: "perfecto para un look atrevido.",
    size: ["S"],
    image: "./short_amarillo_deportivo_1.jpg",
    more_images: ["./short_amarillo_deportivo_1_1.jpg"],
    price: 10.0,
    activo: true,
  },
  {
    id: 23,
    name: "TOP NEGRO UNICOLOR",
    description: "perfecto para un look atrevido.",
    size: ["S"],
    image: "./top_mujer_11_1.jpg",
    more_images: [],
    price: 8.0,
    activo: true,
  },
  {
    id: 24,
    name: "TOP BEIGE UNICOLOR",
    description: "perfecto para un look atrevido.",
    size: ["S"],
    image: "./top_mujer_12.jpg",
    more_images: [],
    price: 8.0,
    activo: true,
  },
  {
    id: 25,
    name: "CAMISETA VERDE MILANO",
    description: "perfecto para un look atrevido.",
    size: ["M"],
    image: "./camiseta_mujer_milano_1.jpg",
    more_images: ["./camiseta_mujer_milano_1_1.jpg"],
    price: 10.0,
    activo: true,
  },
  {
    id: 26,
    name: "TOP CREMA UNICOLOR",
    description: "perfecto para un look atrevido.",
    size: ["S"],
    image: "./top_mujer_crema_1.jpg",
    more_images: [],
    price: 8.0,
    activo: true,
  },
  {
    id: 27,
    name: "CONJUNTO DEPORTIVO DAMA MORADO",
    description: "perfecto para un look atrevido.",
    size: ["S"],
    image: "./conjunto_morado_dama_1.jpg",
    more_images: [
      "./conjunto_morado_dama_1_1.jpg",
      "./conjunto_morado_dama_1_2.jpg",
      "./conjunto_morado_dama_1_3.jpg",
    ],
    price: 20.0,
    activo: true,
  },
  {
    id: 28,
    name: "FALDA SHORT NEGRA",
    description: "perfecto para un look atrevido.",
    size: ["S"],
    image: "./falda_short_negra_1.jpg",
    more_images: ["./falda_short_negra_1_2.jpg", "./falda_short_negra_1_3.jpg"],
    price: 15.0,
    activo: true,
  },
  {
    id: 29,
    name: "CAMISETA MORADA CORTA DAMA",
    description: "perfecto para un look atrevido.",
    size: ["S"],
    image: "./camiseta_corta_morada_dama_1.jpg",
    more_images: ["./camiseta_corta_morada_dama_1_1.jpg"],
    price: 8.0,
    activo: true,
  },
  {
    id: 30,
    name: "CAMISETA VERDE CORTA DAMA",
    description: "perfecto para un look atrevido.",
    size: ["S"],
    image: "./camiseta_corta_verde_dama_2.jpg",
    more_images: [],
    price: 8.0,
    activo: true,
  },
  {
    id: 31,
    name: "CONJUNTO DEPORTIVO DAMA GRIS",
    description: "perfecto para un look atrevido.",
    size: ["S"],
    image: "./conjunto_gris_dama_1.jpg",
    more_images: [
      "./conjunto_gris_dama_1_1.jpg",
      "./conjunto_gris_dama_1_2.jpg",
    ],
    price: 16.0,
    activo: true,
  },
];
